### ISSUE TITLE
Missing data for 2023

### ISSUE THREAD

**Issue by pstadler** [metaodi/openerz#125]
Hey Odi

Trying to query data for 2023, but nothing is being returned[1].

Cheers
Patrick

[1] https://openerz.metaodi.ch/api/calendar.ics?zip=8055&types=cardboard&types=paper&lang=de&start=2023-01-01

**Comment by metaodi** [comment]
I'm working on it, hope I can release tomorrow.

**Comment by pstadler** [comment]
Thanks 👍🏻

**Comment by BadTorro** [comment]
I guess this one is still pending? When I try to fetch data, nothing is returned: 

http://openerz.metaodi.ch/api/calendar.json?zip=8047&start=2023-01-05&end=2023-01-12

Thanks !

**Comment by multipleofzero** [comment]
Hi Odi

Thank you so much for providing this API! Awesome to see that you are still maintaining it. I am among the crowd waiting for 2023 data :). No pressure though.

Cheers!

**Comment by metaodi** [comment]
So the new data is now available, let me know if anything is broken, but it should work now with the 2023 data.

**Comment by pstadler** [comment]
Just checked. Some dates for 8055 seem to be off. Paper and cardboard collection in 8055 happens to be on Tuesdays.

<img width="1034" alt="february" src="https://user-images.githubusercontent.com/600097/210957241-0b3e5d8f-ae64-47c8-b7f4-678ef524e126.png">

<img width="1034" alt="march" src="https://user-images.githubusercontent.com/600097/210957266-3a608683-6e4f-44ba-a6d7-8e77031efe23.png">

API call: https://openerz.metaodi.ch/api/calendar.json?zip=8055&types=cardboard&types=paper&lang=de
Reference: https://www.stadt-zuerich.ch/content/dam/stzh/ted/Deutsch/erz/abfall/eu23/eu23-barrierefrei/221116_ERZ_Entsorgungskalender_2023_55_ba.pdf

**Comment by pstadler** [comment]
Just checked your [data source](https://github.com/metaodi/openerz/blob/main/csv/zurich/zurich.py#L19) and it's clearly wrong on their side.

**Comment by metaodi** [comment]
I will check with ERZ and try to get the data fixed.

**Comment by metaodi** [comment]
The data was fixed and I just loaded it, looks good to me.

**Comment by pstadler** [comment]
Confirmed. That was quick, thanks for caring!
