### ISSUE TITLE
ICS events are 1 day off

### ISSUE THREAD

**Issue by SuperBFG7** [metaodi/openerz#31]
Hi, thanks for the great work.
I tried exporting the ICS version of some of the event and they were always one day off (one day early). While the JSON export is correct, the ICS one uses the correct date for the end-date and the day before for the start date. Example:
http://openerz.herokuapp.com/api/calendar/paper.json?limit=1&zip=8046
http://openerz.herokuapp.com/api/calendar/paper.ics?limit=1&zip=8046

cheers!
Daniel

**Comment by metaodi** [comment]
Thanks for this feedback. I could reproduce this issue, the fix shouldn't be hard. I'll get back to this in a bit.

**Comment by SuperBFG7** [comment]
Thank you! Works perfectly now!

**Comment by metaodi** [comment]
Glad it works for you as well. Thanks for reporting this issue!
