### ISSUE TITLE
Request URL not correct

### ISSUE THREAD

**Issue by SuperBFG7** [metaodi/openerz#32]
The request URL on http://openerz.herokuapp.com is not composed correctly, the format variable is never replaces (worked earlier this month).

Example:
http://openerz.herokuapp.com:80/api/calendar/cardboard{format?}?zip=8046&&&&&&

cheers!
Daniel

**Comment by metaodi** [comment]
Yes this is actually a bug in the hapi-swagger plugin, I'll look into it, I think an earlier version of the plugin didn't have this bug.
