### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by sabberworm** [metaodi/openerz#93]
Hi @metaodi

First of all, thanks a lot for maintaining and hosting this data.

It seems https://openerz.metaodi.ch/ is currently using an expired certificate.

Maybe switch to a letsencrypt cert? According to the [heroku docs](https://devcenter.heroku.com/articles/automated-certificate-management), this should be as simple as `heroku certs:auto:enable` and then removing the manual cert.

**Comment by metaodi** [comment]
Thanks for raising this issue, I'll check with heroku if it really is that simple.
